### ISSUE TITLE
cant compile one f your other projects

### ISSUE THREAD

**Issue by stevefoxuk** [Tnze/esp32_beaconSpam#1]
There is no option to create an issue on your ESP 32 beacon spammer  so hope you dont mind me asking here and wonder if you can help please?

When trying to compile the ESP-32 beacon spammer i get the following - error: cannot convert 'esp_interface_t' to 'wifi_interface_t'

I have zero coding knowledge and trying to google it has not provided any pointers :(

can you help please?

Thanks, Steve.

**Comment by Tnze** [comment]
Oh, this is a project from a long time ago, perhaps because the ESP32 SDK has updated their API? You could try installing the older [ESP32 Arduino Core](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md) (e.g. a 5 years ago version), I don't know.

I still kept my ESP32 board. Maybe I can try fix the compiling error few days later.

**Comment by stevefoxuk** [comment]
It would be great if you got it working, yours appears to be the only beacon spammer for the ESP32 board!

**Comment by Tnze** [comment]
Fixed. It passed the verifying. I didn't try upload yet.

**Comment by stevefoxuk** [comment]
> Fixed. It passed the verifying. I didn't try upload yet.

Compiled, uploaded and working.

You are the man, thankyou!!
